data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors = FALSE, dec=".")
extract <- data[data$Date %in% c("1/2/2007","2/2/2007"),]
active_power <- as.numeric(extract$Global_active_power)
date <-strptime(paste(extract$Date, extract$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
Sub_metering_1 <-as.numeric(extract$Sub_metering_1)
Sub_metering_2 <-as.numeric(extract$Sub_metering_2)
Sub_metering_3 <-as.numeric(extract$Sub_metering_3)
reactive_power <-as.numeric(extract$Global_reactive_power)
voltage <-as.numeric(extract$Voltage)
png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(date, active_power, type="l", xlab = " ", ylab = "Gloabal Active Power", cex=0.2)
plot(date, voltage, type="l", xlab="datetime", ylab = "Voltage")
plot(date, Sub_metering_1, type="l", ylab="Energy Submetering", xlab=" ")
lines(date, Sub_metering_2, type="l", col="red")
lines(date, Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n", lty=1, lwd=2.5, col=c("black","red","blue"))
plot(date, reactive_power, type="l", xlab = "datetime", ylab = "Gloabal_reactive_power", cex=0.2)
dev.off()